### ISSUE TITLE
exception in server tick loop

### ISSUE THREAD

**Issue by Rockiecraft** [ArgenNova/Create-Immersive-Portals#1]
this one is for single player [crash-2023-12-28_12.51.31-server.txt](https://github.com/ArgenNova/Create-Immersive-Portals/files/13788761/crash-2023-12-28_12.51.31-server.txt)
this one is from my server if there is any difference
[crash-2023-12-28_18.59.10-server.txt](https://github.com/ArgenNova/Create-Immersive-Portals/files/13788836/crash-2023-12-28_18.59.10-server.txt)

without the mod i can't load minecraft with immersive portals and create at all, but when i have it installed i can load minecraft but not get into a world. 

i have like 130+ mods so idk if those are causing it or not.

heres the list of all em just in case:
[Reforgium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/reforgium)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Eureka! Ships! for Valkyrien Skies (Forge/Fabric) (by rubydesic)](https://www.curseforge.com/minecraft/mc-mods/eureka-ships)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[Easy Shulker Boxes [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-shulker-boxes)
[Valkyrien Skies (Forge/Fabric) (by triode_)](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Immersive Weathering [FORGE] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Time Control (by Unixkitty)](https://www.curseforge.com/minecraft/mc-mods/time-control)
[Beastly Beacons (by Mindthemoods)](https://www.curseforge.com/minecraft/mc-mods/beastly-beacons)
[Infernal Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion)
[Simple Backups (by MelanX)](https://www.curseforge.com/minecraft/mc-mods/simple-backups)
[Item Collectors (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/item-collectors)
[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[AdoraBuild: Structures (by AdoraBuild)](https://www.curseforge.com/minecraft/mc-mods/adorabuild-structures)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Emotecraft (Forge) (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/emotecraft-forge)
[Accommodations (Japanese Additions) (by Klausster01)](https://www.curseforge.com/minecraft/mc-mods/accommodations-japanese-additions)
[Bigger Stacks (by thanksihadtosignupforthis)](https://www.curseforge.com/minecraft/mc-mods/bigger-stacks)
[Respawning Shulkers (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/respawning-shulkers)
[Create: Crystal Clear (by singularity_cyvack)](https://www.curseforge.com/minecraft/mc-mods/create-crystal-clear)
[Magnesium/Rubidium Extras (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Torchmaster (by xalcon)](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
[End's Phantasm (by Lyof429)](https://www.curseforge.com/minecraft/mc-mods/phantasm)
[Connectedness (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/connectedness)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Lightspeed - Launch optimizations (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/lightspeedmod)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Create Cafe (by Myst)](https://www.curseforge.com/minecraft/mc-mods/create-cafe)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Golden Hopper (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/golden-hopper)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Biome Backport (Some 1.20 Features) (by Myst)](https://www.curseforge.com/minecraft/mc-mods/biome-backport)
[RuOK (by AweiMC)](https://www.curseforge.com/minecraft/mc-mods/ruok)
[Honey Sticky Piston (by MWR____)](https://www.curseforge.com/minecraft/mc-mods/honey-sticky-piston)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[TexTrue's Rubidium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Enhanced Block Entities Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities-reforged-unofficial)
[Simple Shops (by wolforce)](https://www.curseforge.com/minecraft/mc-mods/simple-shops)
[Upgrade Aquatic (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
[Japanese Romaji Converter (Forge/Fabric) (by Meatwo310)](https://www.curseforge.com/minecraft/mc-mods/japanese-romaji-converter)
[Mob Grinding Utils (by vadis365)](https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Just Zoom [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/just-zoom-forge)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Deepslate Tweaks (Forge / Fabric) (by SYCO_3)](https://www.curseforge.com/minecraft/mc-mods/deepslate-tweaks)
[Pick Up Notifier [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[libIPN (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/libipn)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Natural Decoration (by praizazdd7724)](https://www.curseforge.com/minecraft/mc-mods/natural-decoration)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Create: Factory (by antopfr90)](https://www.curseforge.com/minecraft/mc-mods/create-factory)
[Distant Horizons: A Level of Detail mod (by James_Seibel)](https://www.curseforge.com/minecraft/mc-mods/distant-horizons)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Super Mobestiary (by portakalcevheri)](https://www.curseforge.com/minecraft/mc-mods/super-mobestiary)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[Otyacraft Engine [Forge/Fabric] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/otyacraft-engine)
[FPS Boost (by The_TCT)](https://www.curseforge.com/minecraft/mc-mods/better-fps)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Tiered Shulker Boxes (by lukegrahamlandry)](https://www.curseforge.com/minecraft/mc-mods/tiered-shulkers)
[Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Excavation (by IminhaK)](https://www.curseforge.com/minecraft/mc-mods/excavation)
[FPS optimizer (by The_TCT)](https://www.curseforge.com/minecraft/mc-mods/fps-optimizer)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[Embeddium (Rubidium) Extra (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Dave's Building Extended (by Medic_Main_Dave)](https://www.curseforge.com/minecraft/mc-mods/daves-building-extended)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Duckling (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Observable (by tasgon)](https://www.curseforge.com/minecraft/mc-mods/observable)
[CullLessLeaves Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/culllessleaves-reforged)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Even Better Amethyst [Forge] (by betathunder1)](https://www.curseforge.com/minecraft/mc-mods/even-better-amethyst)
[Effective (Forge) (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/effective-forge)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[Panda's Falling Tree's (by ThePandaOliver)](https://www.curseforge.com/minecraft/mc-mods/pandas-falling-trees)
[Iam Music Player [Forge/Fabric] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/iammusicplayer)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[ConnectedTexturesMod (by tterrag1098)](https://www.curseforge.com/minecraft/mc-mods/ctm)
[Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Resourceful Lib (by ThatGravyboat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Name Tag Tweaks (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/name-tag-tweaks)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Tree Harvester (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Plenty of Golems (by alborto06)](https://www.curseforge.com/minecraft/mc-mods/plenty-of-golems)
[Incendium (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/incendium)
[Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Presence Footsteps [Forge] (by Paint_Ninja)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge)
[Japanese Emoji Commands (by Paint_Ninja)](https://www.curseforge.com/minecraft/mc-mods/japanese-emoji-commands)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Create: Bells & Whistles (by sudolev)](https://www.curseforge.com/minecraft/mc-mods/bellsandwhistles)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Staaaaaaaaaaaack (Stxck) (by frankv_)](https://www.curseforge.com/minecraft/mc-mods/staaaaaaaaaaaack)
[Fetzi's Asian Decoration (by NotFetzi)](https://www.curseforge.com/minecraft/mc-mods/fetzis-asian-decoration)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Radon (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radon)
[Inventorio (Forge) (by Lizard_OfOz)](https://www.curseforge.com/minecraft/mc-mods/inventorio-forge)
[Custom Music (Mindthemood's Inspiration Vibes) (by Mindthemoods)](https://www.curseforge.com/minecraft/mc-mods/custom-music-mindthemoods-inspiration-vibes)
[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)

**Comment by ArgenNova** [comment]
The game won't load because of a mod incompatibility between Immersive Portals and one of the other mods installed there.
It's not something this mod could fix.

**Comment by Rockiecraft** [comment]
Thanks. good to know.

**Comment by Rockiecraft** [comment]
forgot to post it on here earlier, but serene seasons is incompatible with immersive portals for some reason. just wanted to leave this here just incase someone runs into similar issues.
