### ISSUE TITLE
Other mod dimensions such as Beyond Earth

### ISSUE THREAD

**Issue by Bebobobo** [ArgenNova/Create-Immersive-Portals#3]
are the portals compatible with other mod dimensions or just the vanilla/preset dimensions? I am trying to find a way to setup interstellar train travel between worlds. Any help is greatly appreciated. Using the 1.19.2 version.

**Comment by ArgenNova** [comment]
It will work as long as it's an immersive portal made without commands. Whether it's modded or vanilla doesn't matter.

**Comment by Bebobobo** [comment]
thanks for the quick response.
